rm ./cold.counter 2> /dev/null
rm ./cold.hwsfile 2> /dev/null
rm ./cold.vkey 2> /dev/null
rm ./kes.vkey 2> /dev/null
rm ./node.cert 2> /dev/null
rm ./stake.hwsfile 2> /dev/null
rm ./stake.vkey 2> /dev/null
rm ./operator-payment.hwsfile 2> /dev/null
rm ./operator-payment.vkey 2> /dev/null
rm ./operator-stake.hwsfile 2> /dev/null
rm ./operator-stake.vkey 2> /dev/null
rm ./operator.witness 2> /dev/null
rm ./owner-stake.hwsfile 2> /dev/null
rm ./owner-stake.vkey 2> /dev/null
rm ./owner.witness 2> /dev/null
rm ./pool.witness 2> /dev/null
rm ./tx.raw 2> /dev/null
rm ./tx-deregister-pool.raw 2> /dev/null
rm ./tx-deregister-pool.signed 2> /dev/null
rm ./tx-register-pool.raw 2> /dev/null
