rm ./cold.vkey 2> /dev/null
rm ./kes.skey 2> /dev/null
rm ./kes.vkey 2> /dev/null
rm ./meta.json 2> /dev/null
rm ./stake.addr 2> /dev/null
rm ./stake.vkey 2> /dev/null
rm ./vrf.skey 2> /dev/null
rm ./vrf.vkey 2> /dev/null
rm ./pool-registration.cert 2> /dev/null
rm ./operator-payment.addr 2> /dev/null
rm ./operator-payment.vkey 2> /dev/null
rm ./operator-stake.vkey 2> /dev/null
rm ./operator.witness 2> /dev/null
rm ./owner-stake.addr 2> /dev/null
rm ./owner-stake.vkey 2> /dev/null
rm ./owner.witness 2> /dev/null
rm ./pool.witness 2> /dev/null
rm ./tx.raw 2> /dev/null
rm ./tx.signed 2> /dev/null
rm ./pool-deregistration.cert 2> /dev/null
rm ./protocol.json 2> /dev/null
rm ./tx-deregister-pool.raw 2> /dev/null
rm ./tx-deregister-pool.signed 2> /dev/null
rm ./node.cert 2> /dev/null
rm ./tx-register-pool.raw 2> /dev/null
rm ./tx-register-pool.signed 2> /dev/null
